// utils/options.ts
export const options = [
  { value: "backend-development", label: "Backend Development" },
  { value: "frontend-development", label: "Frontend Development" },
  { value: "full-stack-development", label: "Full Stack Development" },
  { value: "devops", label: "DevOps" },
  { value: "data-science", label: "Data Science" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "artificial-intelligence", label: "Artificial Intelligence" },
  { value: "blockchain-development", label: "Blockchain Development" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "mobile-app-development", label: "Mobile App Development" },
  { value: "ui-ux-design", label: "UI/UX Design" },
  { value: "graphic-design", label: "Graphic Design" },
  { value: "product-management", label: "Product Management" },
  { value: "project-management", label: "Project Management" },
  { value: "software-testing-qa", label: "Software Testing/QA" },
  { value: "business-analysis", label: "Business Analysis" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "content-creation", label: "Content Creation" },
  { value: "seo", label: "SEO (Search Engine Optimization)" },
  { value: "social-media-management", label: "Social Media Management" },
  { value: "it-support", label: "IT Support" },
  { value: "network-administration", label: "Network Administration" },
  { value: "database-administration", label: "Database Administration" },
  { value: "data-engineering", label: "Data Engineering" },
  { value: "web-development", label: "Web Development" },
  { value: "game-development", label: "Game Development" },
  { value: "ar-vr-development", label: "AR/VR Development" },
  { value: "e-commerce-development", label: "E-commerce Development" },
  { value: "technical-writing", label: "Technical Writing" },
  {
    value: "customer-relationship-management",
    label: "Customer Relationship Management (CRM)",
  },
  { value: "sales", label: "Sales" },
  { value: "financial-analysis", label: "Financial Analysis" },
  { value: "human-resources", label: "Human Resources" },
  { value: "legal-compliance", label: "Legal Compliance" },
  { value: "supply-chain-management", label: "Supply Chain Management" },
  { value: "operations-management", label: "Operations Management" },
  { value: "electrical-engineering", label: "Electrical Engineering" },
  { value: "mechanical-engineering", label: "Mechanical Engineering" },
  { value: "civil-engineering", label: "Civil Engineering" },
];
